
name: Tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'zulu'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Download modified Nether Pathfinder
      run: |
        mkdir -p "$GITHUB_WORKSPACE/.deps"

        curl --fail --location --retry 3 \
          "https://github.com/HackerRouter/nether-pathfinder/releases/download/v1.6-windows-hr.1/nether-pathfinder-1.6-windows-hr.1.jar" \
          --output "$GITHUB_WORKSPACE/.deps/nether-pathfinder.jar"

        echo "D87727EC9336B4A95FA2755E405A72F718090E1502BBB255746788451A8056D3  $GITHUB_WORKSPACE/.deps/nether-pathfinder.jar" \
          | sha256sum --check

    - name: Executing tests
      run: |
        ./gradlew test \
          -Pnether_pathfinder_jar="$GITHUB_WORKSPACE/.deps/nether-pathfinder.jar" \
          -Pnether_pathfinder_version=1.6-windows-hr.1

